[package]
name = "gam_bam_color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.6"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["bundled"]